name: build
on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        go: [1.16]

    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{matrix.go}}

    - name: Check out code
      uses: actions/checkout@v2

    - name: Lint
      shell: bash --noprofile --norc -x -eo pipefail {0}
      run: |
        make lint-pkgs
        make lint

    - name: Test
      run: |
        make test